/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.pemeanan.tiket;

import javax.swing.JOptionPane;

/**
 *
 * @author NA
 */
public class FormMember extends javax.swing.JFrame {
   // private AdminVerivication vAdmin;
    //String ad = vAdmin.getAdver();
    /**
     * Creates new form FormPemesanan
     */
    
    public int monyet = this.monyet;
    @Override
    public void dispose() {
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }
    public FormMember() {
        initComponents();
        this.dispose();
       // if(monyet==1){
       //     tpPesan.remove(pHasil);
            
     //   }
     //   if(monyet==0){
       //     this.tpPesan.setEnabledAt(1, true);
     //   }
        //to hide pane
        //
       /*if (ad.equals("Admin")) 
        {
            this.tpPesan.setEnabledAt(1, true);
        }
        else 
        {
            tpPesan.remove(pHasil);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPesan = new javax.swing.JTabbedPane();
        pIsian = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spDewasa = new javax.swing.JSpinner();
        spBalita = new javax.swing.JSpinner();
        btnPesan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfKTP = new javax.swing.JTextField();
        cbTujuan = new javax.swing.JComboBox<>();
        cbAsal = new javax.swing.JComboBox<>();
        tfTanggal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pIsian.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DEWASA");
        pIsian.add(jLabel2);
        jLabel2.setBounds(110, 310, 150, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NO KTP");
        pIsian.add(jLabel3);
        jLabel3.setBounds(110, 120, 170, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STASIUN ASAL");
        pIsian.add(jLabel4);
        jLabel4.setBounds(110, 200, 150, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STASIUN TUJUAN");
        pIsian.add(jLabel5);
        jLabel5.setBounds(110, 240, 150, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("INFANT");
        pIsian.add(jLabel6);
        jLabel6.setBounds(110, 280, 150, 30);
        pIsian.add(spDewasa);
        spDewasa.setBounds(280, 310, 70, 30);
        pIsian.add(spBalita);
        spBalita.setBounds(280, 280, 70, 30);

        btnPesan.setText("Pesan Sekarang");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });
        pIsian.add(btnPesan);
        btnPesan.setBounds(540, 320, 120, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TANGGAL KEBERANGKATAN");
        pIsian.add(jLabel7);
        jLabel7.setBounds(110, 160, 170, 30);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NAMA");
        pIsian.add(jLabel8);
        jLabel8.setBounds(110, 80, 170, 30);

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        pIsian.add(tfNama);
        tfNama.setBounds(280, 80, 150, 30);

        tfKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKTPActionPerformed(evt);
            }
        });
        pIsian.add(tfKTP);
        tfKTP.setBounds(280, 120, 150, 30);

        cbTujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya", "Malang", "Kediri", "Blitar" }));
        pIsian.add(cbTujuan);
        cbTujuan.setBounds(280, 240, 150, 30);

        cbAsal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya", "Malang", "Kediri", "Blitar" }));
        pIsian.add(cbAsal);
        cbAsal.setBounds(280, 200, 150, 30);
        pIsian.add(tfTanggal);
        tfTanggal.setBounds(280, 160, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/pemeanan/tiket/bg untuk pesan tiket.png"))); // NOI18N
        pIsian.add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 370);

        tpPesan.addTab("Form Pemesanan", pIsian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpPesan, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setBounds(0, 0, 710, 436);
    }// </editor-fold>//GEN-END:initComponents

    private void tfKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKTPActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        String nama=tfNama.getText();
        String nomor = tfKTP.getText();
        String tanggal = tfTanggal.getDate().toString();
        String asal = (String)cbAsal.getSelectedItem( );
        String tujuan = (String)cbTujuan.getSelectedItem( );
        int dws = (Integer) spDewasa.getValue();
        int blta = (Integer) spBalita.getValue();
        
        if(asal == "Malang"){
            int teko = 300;
        }else if(asal == "Blitar"){
            int teko = 200;
        }else if(asal == "Kediri"){
            int teko = 100;
        }else if(asal == "Surabaya"){
            int teko = 600;
        }
        
        if(tujuan == "Malang"){
            int nyang = 300;
        }else if(tujuan == "Blitar"){
            int nyang = 200;
        }else if(tujuan == "Kediri"){
            int nyang = 100;
        }else if(tujuan == "Surabaya"){
            int nyang = 600;
        }
        
        int tharga = ((11250 * dws )+(5500 * blta));

        String tarif = "Rp."+tharga;
        String dwsa = ""+dws;
        String blt = ""+blta;
        String tharga2 = ""+tharga;
        String tanggal2= ""+tanggal;
        
        if (validasi()) {
        tiketmember x=new tiketmember(nama, nomor, tanggal, asal, tujuan, dwsa, blt, tharga2, tarif);
        x.setVisible(true);
        
        String SQL = "INSERT INTO tb_pendaftar (no_ktp,nama,tanggal,asal,tujuan,infant,dewasa,tarif_total) "
                    + "VALUES('"+nomor+"','"+nama+"','"+tanggal+"','"+asal+"','"+tujuan+"',"+blta+","+dws+","+tharga+")";
            int status = connection.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                //selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
       // new Result(nomor, tanggal, asal, tujuan, tarif).setVisible(false);
    }//GEN-LAST:event_btnPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMember().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesan;
    private javax.swing.JComboBox<String> cbAsal;
    private javax.swing.JComboBox<String> cbTujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pIsian;
    private javax.swing.JSpinner spBalita;
    private javax.swing.JSpinner spDewasa;
    private javax.swing.JTextField tfKTP;
    private javax.swing.JTextField tfNama;
    private com.toedter.calendar.JDateChooser tfTanggal;
    private javax.swing.JTabbedPane tpPesan;
    // End of variables declaration//GEN-END:variables

    private boolean validasi() {
        boolean benar = false;
        
        String nama = tfNama.getText();
        String nomor = tfKTP.getText();
        String tanggal = tfTanggal.getDate().toString();
        String asal = (String)cbAsal.getSelectedItem();
        String tujuan = (String)cbTujuan.getSelectedItem( );
        int dewasa = (Integer) spDewasa.getValue();
        String tanggal2 = ""+tanggal; 
        
        if (nama.equals("")) {
            JOptionPane.showMessageDialog(this, "Anda belum mengisi nama", "Validasi", JOptionPane.WARNING_MESSAGE);
            benar = false;
        }
        else if (nomor.equals("")) {
            JOptionPane.showMessageDialog(this, "Anda belum mengisi nomor ktp", "Validasi", JOptionPane.WARNING_MESSAGE);
            benar = false;
        }
        else if (tanggal2.equals("")) {
            JOptionPane.showMessageDialog(this, "Anda belum mengisi tanggal keberangkatan", "Validasi", JOptionPane.WARNING_MESSAGE);
            benar = false;
        }
        else if (asal.equals(tujuan)) {
            JOptionPane.showMessageDialog(this, "Pastikan stasiun asal dan tujuan Anda benar", "Validasi", JOptionPane.WARNING_MESSAGE);
            benar = false;
                        
        }
        else if (dewasa<1) {
            JOptionPane.showMessageDialog(this, "Harus ada orang dewasa", "Validasi", JOptionPane.WARNING_MESSAGE);
            benar = false;
        }
        else{ benar = true; }
        
        return benar;
    }
}
