/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.pemeanan.tiket;

/**
 *
 * @author Smktelkom
 */
public class tiketmember extends javax.swing.JFrame{ 
    
    
    public tiketmember(String nama, String nomor, String tanggal, String tujuan, String asal, String dws, String blta, String tharga, String tarif) {
        initComponents();
        
        this.nama.setText(nama);
        this.noKtp.setText(nomor);
        this.staAsal.setText(asal);
        this.staTujuan.setText(tujuan);
        this.tanggal.setText(tanggal);
        this.dewasa.setText(dws);
        this.balita.setText(blta);
        this.total.setText(tarif);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        noKtp = new javax.swing.JLabel();
        staAsal = new javax.swing.JLabel();
        staTujuan = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        dewasa = new javax.swing.JLabel();
        balita = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel8.setText("Total Harga");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 390, 130, 25);
        getContentPane().add(total);
        total.setBounds(180, 390, 210, 25);

        jLabel11.setText("NO KTP");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 150, 130, 25);

        jLabel12.setText("Stasiun Asal");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 190, 130, 25);

        jLabel13.setText("Stasiun Tujuan");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 230, 130, 25);

        jLabel14.setText("Tanggal Keberangkatan");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 270, 130, 25);

        jLabel15.setText("Dewasa");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 310, 130, 25);

        jLabel16.setText("Balita");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 350, 130, 25);

        jLabel17.setText("Nama Pemesan");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 110, 130, 25);
        getContentPane().add(nama);
        nama.setBounds(180, 110, 210, 25);
        getContentPane().add(noKtp);
        noKtp.setBounds(180, 150, 210, 25);
        getContentPane().add(staAsal);
        staAsal.setBounds(180, 190, 210, 25);
        getContentPane().add(staTujuan);
        staTujuan.setBounds(180, 230, 210, 25);
        getContentPane().add(tanggal);
        tanggal.setBounds(180, 270, 210, 25);
        getContentPane().add(dewasa);
        dewasa.setBounds(180, 310, 210, 25);
        getContentPane().add(balita);
        balita.setBounds(180, 350, 210, 25);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 340, 700, 100);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiketmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiketmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiketmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiketmember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balita;
    private javax.swing.JLabel dewasa;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel noKtp;
    private javax.swing.JLabel staAsal;
    private javax.swing.JLabel staTujuan;
    private javax.swing.JLabel tanggal;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
